### ISSUE TITLE
[Feat] 상품(책) CRUD 구현

### ISSUE THREAD

**Issue by minnseong** [likelion-backendschool/FinalProject_KangMinSeong_team7#13]
## Description
상품(책) CRUD 구현

## To-do
- [ ] Product 엔티티 설계
- [ ] Product 컨트롤러, 서비스, 리포지토리 추가
- [ ] 상품(책) CRUD 구현
