### ISSUE TITLE
[Test] Controller, Service 테스트 코드 작성 

### ISSUE THREAD

**Issue by minnseong** [likelion-backendschool/FinalProject_KangMinSeong_team7#20]
## Description
각 컨트롤러와 서비스의 테스트 코드 작성

## To-do
- [x] MemberController 테스트 코드 작성
- [x] MemberService 테스트 코드 작성
- [x] PostController 테스트 코드 작성
- [x] PostService 테스트 코드 작성
- [x] ProductController 테스트 코드 작성
- [x] ProductService 테스트 코드 작성
- [x] PostHashTagService 테스트 코드 작성
- [x] PostKeywordService 테스트 코드 작성
