### ISSUE TITLE
[Test] 테스트 코드 작성 및 Jacoco 추가

### ISSUE THREAD

**Issue by minnseong** [likelion-backendschool/FinalProject_KangMinSeong_team7#45]
## Description
테스트 코드 수정 및 추가, Jacoco 의존성 주입

## To-do
- [ ] Jacoco 의존성 주입
- [ ] 테스트 코드 추가
- [ ] 테스트 코드 수정
